# Generated by Django 3.2.11 on 2022-03-13 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='plays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moveType', models.PositiveSmallIntegerField(choices=[(0, 'UP'), (1, 'DOWN'), (2, 'LEFT'), (3, 'RIGHT')])),
                ('spaces', models.IntegerField()),
                ('gameRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.gamerecord')),
            ],
        ),
    ]
