# Generated by Django 3.2.11 on 2022-03-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_gamerecord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='absDistance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
