# Generated by Django 3.2.11 on 2022-03-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_gamerecord_absdistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
